# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_fault_injection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fault(object):
    def setupUi(self, Fault):
        Fault.setObjectName("Fault")
        Fault.resize(362, 325)
        self.groupBox = QtWidgets.QGroupBox(Fault)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 321, 251))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 70, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 100, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 40, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 130, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.modeBox = QtWidgets.QComboBox(self.groupBox)
        self.modeBox.setGeometry(QtCore.QRect(190, 70, 111, 22))
        self.modeBox.setObjectName("modeBox")
        self.erBox = QtWidgets.QComboBox(self.groupBox)
        self.erBox.setGeometry(QtCore.QRect(190, 100, 111, 22))
        self.erBox.setObjectName("erBox")
        self.exe_timesBox = QtWidgets.QComboBox(self.groupBox)
        self.exe_timesBox.setGeometry(QtCore.QRect(190, 40, 111, 22))
        self.exe_timesBox.setObjectName("exe_timesBox")
        self.bfmBox = QtWidgets.QComboBox(self.groupBox)
        self.bfmBox.setGeometry(QtCore.QRect(190, 130, 111, 22))
        self.bfmBox.setObjectName("bfmBox")
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setGeometry(QtCore.QRect(10, 160, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.groupBox)
        self.label_6.setGeometry(QtCore.QRect(10, 190, 101, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.mem_startBox = QtWidgets.QComboBox(self.groupBox)
        self.mem_startBox.setGeometry(QtCore.QRect(190, 160, 111, 22))
        self.mem_startBox.setObjectName("mem_startBox")
        self.mem_sizeBox = QtWidgets.QComboBox(self.groupBox)
        self.mem_sizeBox.setGeometry(QtCore.QRect(190, 190, 111, 22))
        self.mem_sizeBox.setObjectName("mem_sizeBox")
        self.ApplyButton = QtWidgets.QPushButton(Fault)
        self.ApplyButton.setGeometry(QtCore.QRect(270, 280, 75, 23))
        self.ApplyButton.setObjectName("ApplyButton")

        self.retranslateUi(Fault)
        QtCore.QMetaObject.connectSlotsByName(Fault)

    def retranslateUi(self, Fault):
        _translate = QtCore.QCoreApplication.translate
        Fault.setWindowTitle(_translate("Fault", "故障注入配置"))
        self.groupBox.setTitle(_translate("Fault", "故障注入参数"))
        self.label.setText(_translate("Fault", "模 式："))
        self.label_2.setText(_translate("Fault", "错误率："))
        self.label_3.setText(_translate("Fault", "次 数："))
        self.label_4.setText(_translate("Fault", "翻转类型："))
        self.label_5.setText(_translate("Fault", "内存起始地址："))
        self.label_6.setText(_translate("Fault", "内存空间尺寸："))
        self.ApplyButton.setText(_translate("Fault", "确定"))
